CREATE EXTENSION IF NOT EXISTS postgis_raster;

CREATE TABLE all_parameters_urban_centers (
	urban_center_id int4 NULL,
	name_main varchar(255) NULL,
	iso_a3 varchar(3) NULL,
	country_id int4 NULL,
	continent varchar(23) NULL,
	region_wb varchar(26) NULL,
	subregion varchar(25) NULL,
	ghspop float8 NULL,
	ghspop_class text NULL,
	total_area_sqkm numeric NULL,
	shdi numeric NULL,
	shdi_class text NULL,
	osm_building_area_sqkm numeric NULL,
	osm_building_area_sqkm_2023 numeric NULL,
	osm_building_area_sqkm_2022 numeric NULL,
	osm_building_area_sqkm_2021 numeric NULL,
	osm_building_area_sqkm_2020 numeric NULL,
	osm_building_area_sqkm_2019 numeric NULL,
	osm_building_area_sqkm_2018 numeric NULL,
	osm_building_area_sqkm_2017 numeric NULL,
	osm_building_area_sqkm_2016 numeric NULL,
	osm_building_area_sqkm_2015 numeric NULL,
	osm_building_area_sqkm_2014 numeric NULL,
	osm_building_area_sqkm_2013 numeric NULL,
	osm_building_area_sqkm_2012 numeric NULL,
	osm_building_area_sqkm_2011 numeric NULL,
	osm_building_area_sqkm_2010 numeric NULL,
	osm_building_area_sqkm_2009 numeric NULL,
	osm_building_area_sqkm_2008 numeric NULL,
	reference_building_area_sqkm numeric NULL,
	reference_osm_completeness numeric NULL,
	humanitarian_osm_building_area_sqkm float8 NULL,
	corporate_osm_building_area_sqkm float8 NULL,
	microsoft_building_area_sqkm numeric NULL,
	geom public.geometry(polygon, 4326) NULL,
	centroid public.geometry NULL,
	PRIMARY KEY (urban_center_id)
);
CREATE INDEX all_parameters_urban_centers_idx ON all_parameters_urban_centers USING gist (geom);

CREATE TABLE all_parameters_urban_centers_grid (
	id int8 NULL,
	urban_center_id int4 NULL,
	name_main varchar(255) NULL,
	iso_a3 varchar(3) NULL,
	country_id int4 NULL,
	continent varchar(23) NULL,
	region_wb varchar(26) NULL,
	osm_building_area_sqkm float8 NULL,
	reference_building_count int8 NULL,
	reference_building_area_sqkm numeric NULL,
	reference_osm_completeness float8 NULL,
	osm_motorway_roads_length_km float8 NULL,
	osm_motorway_roads_length_km_moran float8 NULL,
	osm_other_major_roads_length_km float8 NULL,
	osm_other_major_roads_length_km_moran float8 NULL,
	osm_airports_area_sqkm float8 NULL,
	osm_railway_length_km float8 NULL,
	wsf_built_up_area_sqkm float8 NULL,
	ghs_built_up_area_sqkm numeric(21, 8) NULL,
	ghspop int4 NULL,
	vnl int4 NULL,
	tree_cover_sqkm float8 NULL,
	shrubland_sqkm float8 NULL,
	grassland_sqkm float8 NULL,
	cropland_sqkm float8 NULL,
	built_up_sqkm float8 NULL,
	sparse_vegetation_sqkm float8 NULL,
	snow_and_ice_sqkm float8 NULL,
	permanent_water_bodies_sqkm float8 NULL,
	herbaceous_wetland_sqkm float8 NULL,
	mangroves_sqkm float8 NULL,
	moss_and_lichen_sqkm float8 NULL,
	total_sqkm float8 NULL,
	fossil_fuel float8 NULL,
	ghspop_moran_loc float8 NULL,
	built_up_sqkm_moran_loc float8 NULL,
	shdi numeric NULL,
	shdi_class text NULL,
	ghspop_city float8 NULL,
	ghspop_class text NULL,
	gdp_2015 float8 NULL,
	area_sqkm_city numeric NULL,
	geom public.geometry(polygon, 4326) NULL,
	PRIMARY KEY (id, urban_center_id)
);
CREATE INDEX all_parameters_urban_centers_grid_idx ON all_parameters_urban_centers_grid USING gist (geom);

CREATE TABLE reference_data_urban_centers_grid_raw (
	grid_fid int4 NULL,
	"source" text NULL,
	building_count int8 NULL,
	building_area_sqkm numeric NULL,
	geom public.geometry(polygon, 4326) NULL,
	PRIMARY KEY(grid_fid, "source")
);

create table microsoft_buildings_urban_centers_grid_new (
	grid_id	 bigint,
	urban_center_id int,
	urban_center_name varchar,
	iso_a3 varchar,
	quadkey varchar,
	ms_building_count int,
	ms_building_area_sq_m numeric,
	sample_building_footprint public.geometry,
	grid_wkt public.geometry
);