DROP TABLE IF EXISTS data_preparation.osm_user_contributions_per_project_per_day;
CREATE TABLE data_preparation.osm_user_contributions_per_project_per_day (
	project_id int4 NOT NULL,
	"day" timestamp NOT NULL,
	userid int4 NOT NULL,
	building_change float8 NULL,
	highway_change float8 NULL,
	landuse_change float8 NULL,
	remainder_change float8 NULL,
	healthcare_change float8 NULL,
	places_change float8 NULL,
	amenities_change float8 NULL,
	building_creation float8 NULL,
	highway_creation float8 NULL,
	landuse_creation float8 NULL,
	remainder_creation float8 NULL,
	healthcare_creation float8 NULL,
	places_creation float8 NULL,
	amenities_creation float8 NULL,
	building_deletion float8 NULL,
	highway_deletion float8 NULL,
	landuse_deletion float8 NULL,
	remainder_deletion float8 NULL,
	healthcare_deletion float8 NULL,
	places_deletion float8 NULL,
	amenities_deletion float8 NULL,
	total_count int4 NULL
);

DROP TABLE IF EXISTS data_preparation.projects;
CREATE TABLE data_preparation.projects (
	project_id int4 NULL,
	status int4 NULL,
	created timestamp NULL,
	priority int4 NULL,
	default_locale varchar(10) NULL,
	author_id int8 NULL,
	mapper_level int4 NULL,
	private bool NULL,
	changeset_comment varchar NULL,
	due_date timestamp NULL,
	imagery varchar NULL,
	josm_preset varchar NULL,
	last_updated timestamp NULL,
	mapping_types _int4 NULL,
	total_tasks int4 NULL,
	tasks_mapped int4 NULL,
	tasks_validated int4 NULL,
	tasks_bad_imagery int4 NULL,
	license_id int4 NULL,
	centroid public.geometry(point, 4326) NULL,
	geometry public.geometry(multipolygon, 4326) NULL,
	task_creation_mode int4 NULL,
	mapping_editors _int4 NULL,
	validation_editors _int4 NULL,
	osmcha_filter_id varchar NULL,
	enforce_random_task_selection bool NULL,
	id_presets _varchar NULL,
	featured bool NULL,
	country _varchar NULL,
	organisation_id int4 NULL,
	mapping_permission int4 NULL,
	validation_permission int4 NULL,
	rapid_power_user bool NULL,
	extra_id_params varchar NULL,
	progress_email_sent bool NULL,
	geometry_mollweide public.geometry NULL,
	centroid_mollweide public.geometry NULL,
	ne_name varchar NULL,
	ne_id int4 NULL,
	ne_iso_a3 varchar NULL,
	region_name varchar NULL,
	region_id int4 NULL
);